### ISSUE TITLE
Failure caused by empty variable

### ISSUE THREAD

**Issue by orthorhombic** [maxhoesel-ansible/ansible-collection-borgbackup#135]
When there is nothing in the variable, the below statement causes a failure even when wrapped in the `when` block:

https://github.com/maxhoesel-ansible/ansible-collection-borgbackup/blob/2e90926002b014486a091245b468eb96eefec17c/roles/borgmatic/tasks/ssh.yml#L49C85-L49C85
```yaml
    - name: known_hosts are registered
      known_hosts:
        name: "{{ (item.0.item.split('@').1).split(':').0 }}"
        key: "{{ item.1 }}"
        path: "{{ borgmatic_ssh_known_hosts_file }}"
      loop: "{{ borgmatic_ssh_fingerprints.results | subelements('stdout_lines') }}"
      no_log: yes # reduce log spam a little bit
```

From some quick testing, the below line seems to work as a replacement.
`loop: "{{ borgmatic_ssh_fingerprints.results | d([]) | subelements('stdout_lines', skip_missing=true) }}"`

Reference:
https://stackoverflow.com/questions/72802449/ansible-obj-must-be-a-list-of-dicts-or-a-nested-dict-error-conditional-check
