### ISSUE TITLE
config.yaml is created when borgmatic_manage_config: false

### ISSUE THREAD

**Issue by orthorhombic** [maxhoesel-ansible/ansible-collection-borgbackup#179]
Thanks for the great ansible roles!

I use maxhoesel.borgbackup.borgmatic mostly to manage the scheduling of multiple config files that I set up in `/etc/borgmatic/borgmatic.d`. As a result, I'm using the extension with the following options:
```yaml
borgmatic_setup_backup: true
borgmatic_manage_config: false
```
Unfortunately, this configuration results in the creation of a mostly empty config.yaml that fails at the `Initialize repos` step. Would it be acceptable to add `when: borgmatic_manage_config` as in the following block to avoid the extra file from getting created?

```yaml
    - name: Config is installed
      template:
        src: config.yaml.j2
        dest: "{{ borgmatic_config_path }}/config.yaml"
        owner: root
        group: root
        mode: "640"
      when: borgmatic_manage_config
```

https://github.com/maxhoesel-ansible/ansible-collection-borgbackup/blob/4948279f29276878cfe85d71314b1279acc52ad8/roles/borgmatic/tasks/main.yml#L35C1-L41C20
